# Generated by Django 4.0.5 on 2022-07-28 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_alter_review_stars_movie_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='directors',
            new_name='director',
        ),
    ]
