# Generated by Django 4.0.5 on 2022-07-30 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_movie_director'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='director',
            new_name='directors',
        ),
    ]
